# Generated by Django 5.1.3 on 2024-11-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PImage', models.ImageField(upload_to='images/')),
                ('Pname', models.CharField(max_length=200)),
                ('Pdescription', models.TextField()),
                ('Pprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
